### PR TITLE
feat(python): Update to 3.12

### PR DESCRIPTION
**Pull request by henrikstranneheim**
### Added

-

### Changed

-

### Fixed

-

### How to prepare for test

- [ ] Ssh to relevant server (depending on type of change)
- [ ] Use stage: `us`
- [ ] Paxa the environment: `paxa`
- [ ] Install on stage (example for Hasta):
    ```shell
    bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-stage.sh -e S_crunchy -t crunchy -b update-python
    ```

### How to test

- [ ] Do ...

### Expected test outcome

- [ ] Check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review

- [ ] Tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a

- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan

- [ ] Document in ...
- [ ] Deploy this branch on ...
- [ ] Inform to ...

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
```
[henrik.stranneheim@hasta:~] [S_base] $ conda remove --name S_crunchy --all

Remove all packages in environment /home/proj/stage/bin/miniconda3/envs/S_crunchy:


## Package Plan ##

  environment location: /home/proj/stage/bin/miniconda3/envs/S_crunchy


The following packages will be REMOVED:

  _libgcc_mutex-0.1-conda_forge
  _openmp_mutex-4.5-2_gnu
  bzip2-1.0.8-h7f98852_4
  c-ares-1.18.1-h7f98852_0
  ca-certificates-2022.9.24-ha878542_0
  htslib-1.16-h6bc39ce_0
  keyutils-1.6.1-h166bdaf_0
  krb5-1.19.3-h3790be6_0
  ld_impl_linux-64-2.36.1-hea4e1c9_2
  libcurl-7.83.1-h7bff187_0
  libdeflate-1.13-h166bdaf_0
  libedit-3.1.20191231-he28a2e2_2
  libev-4.33-h516909a_1
  libffi-3.4.2-h7f98852_5
  libgcc-ng-12.1.0-h8d9b700_16
  libgomp-12.1.0-h8d9b700_16
  libnghttp2-1.47.0-hdcd2b5c_1
  libnsl-2.0.0-h7f98852_0
  libssh2-1.10.0-haa6b8db_3
  libstdcxx-ng-12.1.0-ha89aaad_16
  libuuid-2.32.1-h7f98852_1000
  libzlib-1.2.12-h166bdaf_3
  ncurses-6.3-h27087fc_1
  openssl-1.1.1s-h166bdaf_0
  pip-22.2.2-pyhd8ed1ab_0
  python-3.10.2-h85951f9_4_cpython
  readline-8.1-h46c0cb4_0
  samtools-1.16.1-h6899075_1
  setuptools-65.3.0-pyhd8ed1ab_1
  sqlite-3.37.0-h9cd32fc_0
  tk-8.6.12-h27826a3_0
  tzdata-2022e-h191b570_0
  wheel-0.37.1-pyhd8ed1ab_0
  xz-5.2.6-h166bdaf_0
  zlib-1.2.12-h166bdaf_3


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

**Comment by henrikstranneheim** [comment]
```
[henrik.stranneheim@hasta:~] [S_base] $ cg compress fastq -c justhusky
Called undefined __fields__ on HousekeeperAPI, please wrap
Running compress FASTQ
Searching for FASTQ files in case justhusky
Updating compress api
Set dry run to False
Check if FASTQ compression is possible for earlycasualcaiman
Found file earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001_R1_001.fastq.gz
Found file earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001_R2_001.fastq.gz
Check if FASTQ pair exists
File /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001_R1_001.fastq.gz was changed 2023-12-21 08:34:22.868260
Check if compression possible for run HHT5NDSXX_HapMap_S26_L001
Check if pending compression file exists
/home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001.crunchy.pending.txt does not exist
Compression/decompression is not running
Check if SPRING archive file exists
/home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001.spring does not exist
Compressing /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001_R1_001.fastq.gz and /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001_R2_001.fastq.gz for sample earlycasualcaiman into SPRING format
Creating pending flag /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001.crunchy.pending.txt
Created temporary dir /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/spring_o8e7h5op_compress
Submit sbatch /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001_compress_fastq.sh
Running command sbatch /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001_compress_fastq.sh
Submitted batch job 7304541
Fastq compression running as job 7304541


henrik.stranneheim@hasta:~] [S_base] $ scontrol show jobid=7304541
JobId=7304541 JobName=earlycasualcaiman_HHT5NDSXX_HapMap_S26_L001_fastq_to_spring
   UserId=henrik.stranneheim(1265) GroupId=users(100) MCS_label=N/A
   Priority=109 Nice=0 Account=development QOS=maintenance WCKey=*default
   JobState=PENDING Reason=Priority Dependency=(null)
   Requeue=1 Restarts=0 BatchFlag=1 Reboot=0 ExitCode=0:0
   RunTime=00:00:00 TimeLimit=1-00:00:00 TimeMin=N/A
   SubmitTime=2024-09-23T11:19:03 EligibleTime=2024-09-23T11:19:03
   AccrueTime=2024-09-23T11:19:03
   StartTime=Unknown EndTime=Unknown Deadline=N/A
   PreemptTime=None SuspendTime=None SecsPreSuspend=0
   LastSchedEval=2024-09-23T11:25:30
   Partition=core AllocNode:Sid=hasta:143251
   ReqNodeList=(null) ExcNodeList=(null)
   NodeList=(null)
   NumNodes=1 NumCPUs=12 NumTasks=12 CPUs/Task=1 ReqB:S:C:T=0:0:*:*
   TRES=cpu=12,mem=50G,node=1,billing=12
   Socks/Node=* NtasksPerN:B:S:C=0:0:*:* CoreSpec=*
   MinCPUsNode=10 MinMemoryNode=50G MinTmpDiskNode=0
   Features=(null) DelayBoot=00:00:00
   OverSubscribe=OK Contiguous=0 Licenses=(null) Network=(null)
   Command=/home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001_compress_fastq.sh
   WorkDir=/home/henrik.stranneheim
   StdErr=/home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/earlycasualcaiman_HHT5NDSXX_HapMap_S26_L001_fastq_to_spring.stderr
   StdIn=/dev/null
   StdOut=/home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/earlycasualcaiman_HHT5NDSXX_HapMap_S26_L001_fastq_to_spring.stdout
   Power=

**Comment by henrikstranneheim** [comment]
### Adding proxy bin and container
```
[henrik.stranneheim@hasta:~] [S_base] $ cat /home/proj/stage/bin/miniconda3/envs/S_crunchy/bin/spring
#!/bin/bash
BIND_DIR=/home/proj/stage/demultiplexed-runs,/home/proj/stage/housekeeper-bundles,/home/proj/stage/rare-disease/cases
DIR=$(dirname "$(readlink -f "$0")")
CONDA_ENV_DIR="$(dirname "$DIR")"
singularity exec --bind "$BIND_DIR" "$CONDA_ENV_DIR"/share/containers/spring.sif  spring "$@"
[henrik.stranneheim@hasta:~] [S_base] $ ls /home/proj/stage/bin/miniconda3/envs/S_crunchy/bin/spring
/home/proj/stage/bin/miniconda3/envs/S_crunchy/bin/spring

**Comment by henrikstranneheim** [comment]
Fixed cointainers,
```
[henrik.stranneheim@hasta:~] [S_base] $ sbatch /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001_compress_fastq.sh
Submitted batch job 7305786
[henrik.stranneheim@hasta:~] [S_base] $ scontrol show jobid=7305786
JobId=7305786 JobName=earlycasualcaiman_HHT5NDSXX_HapMap_S26_L001_fastq_to_spring
   UserId=henrik.stranneheim(1265) GroupId=users(100) MCS_label=N/A
   Priority=105 Nice=0 Account=development QOS=maintenance WCKey=*default
   JobState=PENDING Reason=Resources Dependency=(null)
   Requeue=1 Restarts=0 BatchFlag=1 Reboot=0 ExitCode=0:0
   RunTime=00:00:00 TimeLimit=1-00:00:00 TimeMin=N/A
   SubmitTime=2024-09-24T10:48:27 EligibleTime=2024-09-24T10:48:27
   AccrueTime=2024-09-24T10:48:27
   StartTime=2024-09-24T16:53:32 EndTime=2024-09-25T16:53:32 Deadline=N/A
   PreemptTime=None SuspendTime=None SecsPreSuspend=0
   LastSchedEval=2024-09-24T10:48:42
   Partition=core AllocNode:Sid=hasta:104234
   ReqNodeList=(null) ExcNodeList=(null)
   NodeList=(null) SchedNodeList=compute-0-17
   NumNodes=1 NumCPUs=12 NumTasks=12 CPUs/Task=1 ReqB:S:C:T=0:0:*:*
   TRES=cpu=12,mem=50G,node=1,billing=12
   Socks/Node=* NtasksPerN:B:S:C=0:0:*:* CoreSpec=*
   MinCPUsNode=10 MinMemoryNode=50G MinTmpDiskNode=0
   Features=(null) DelayBoot=00:00:00
   OverSubscribe=OK Contiguous=0 Licenses=(null) Network=(null)
   Command=/home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001_compress_fastq.sh
   WorkDir=/home/henrik.stranneheim
   StdErr=/home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/earlycasualcaiman_HHT5NDSXX_HapMap_S26_L001_fastq_to_spring.stderr
   StdIn=/dev/null
   StdOut=/home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/earlycasualcaiman_HHT5NDSXX_HapMap_S26_L001_fastq_to_spring.stdout
   Power=

**Comment by henrikstranneheim** [comment]
### Compressiom, 👍 
```
[henrik.stranneheim@hasta:~] [base] $ cat /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/earlycasualcaiman_HHT5NDSXX_HapMap_S26_L001_fastq_to_spring.stderr
[2024-09-24T10:49:44] Running on: compute-0-9.local
2024-09-24 08:49:59 compute-0-9.local crunchy.command[182682] INFO Initialising Process with binary: spring
2024-09-24 08:49:59 compute-0-9.local crunchy.command[182682] INFO Use base call ['spring']
2024-09-24 08:49:59 compute-0-9.local crunchy.command[182682] INFO Initialising Process with binary: samtools
2024-09-24 08:49:59 compute-0-9.local crunchy.command[182682] INFO Use base call ['samtools']
2024-09-24 08:49:59 compute-0-9.local crunchy.cli.base[182682] INFO Running crunchy
2024-09-24 08:49:59 compute-0-9.local crunchy.cli.compress_cmd[182682] INFO Running compress fastq
2024-09-24 08:49:59 compute-0-9.local crunchy.compress[182682] INFO Compressing /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001_R1_001.fastq.gz and /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001_R2_001.fastq.gz to /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001.spring
2024-09-24 08:49:59 compute-0-9.local crunchy.command[182682] INFO File(s) are gzipped
2024-09-24 08:49:59 compute-0-9.local crunchy.command[182682] INFO Compressing fastq to spring
2024-09-24 08:49:59 compute-0-9.local crunchy.command[182682] INFO Running command spring -c -i /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001_R1_001.fastq.gz /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001_R2_001.fastq.gz -o /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001.spring -t 12 -g --working-dir /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/spring_o8e7h5op_compress
2024-09-24 10:32:28 compute-0-9.local crunchy.command[182682] INFO Spring compression succesfully completed!
2024-09-24 10:32:28 compute-0-9.local crunchy.command[182682] INFO Time to compress: 6134
2024-09-24 10:32:28 compute-0-9.local crunchy.integrity[182682] INFO Create checksum for /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001_R1_001.fastq.gz
2024-09-24 10:32:28 compute-0-9.local crunchy.integrity[182682] INFO Use sha256
2024-09-24 10:32:28 compute-0-9.local crunchy.integrity[182682] INFO Unzip before counting checksum
2024-09-24 10:45:09 compute-0-9.local crunchy.integrity[182682] INFO Checksum created
2024-09-24 10:45:09 compute-0-9.local crunchy.integrity[182682] INFO Create checksum for /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001_R2_001.fastq.gz
2024-09-24 10:45:09 compute-0-9.local crunchy.integrity[182682] INFO Use sha256
2024-09-24 10:45:09 compute-0-9.local crunchy.integrity[182682] INFO Unzip before counting checksum
2024-09-24 10:57:19 compute-0-9.local crunchy.integrity[182682] INFO Checksum created
2024-09-24 10:57:19 compute-0-9.local crunchy.metadata[182682] INFO Dumping spring metadata to /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001.json
2024-09-24 10:57:19 compute-0-9.local crunchy.cli.decompress_cmd[182682] INFO Running decompress spring
2024-09-24 10:57:19 compute-0-9.local crunchy.decompress[182682] INFO Decompressing /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001.spring to /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001_R1_001.fastq.spring.fastq and /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001_R2_001.fastq.spring.fastq
2024-09-24 10:57:19 compute-0-9.local crunchy.command[182682] INFO Decompressing spring compressed file
2024-09-24 10:57:19 compute-0-9.local crunchy.command[182682] INFO Running command spring -d -i /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001.spring -o /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001_R1_001.fastq.spring.fastq /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001_R2_001.fastq.spring.fastq --working-dir /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/spring_o8e7h5op_compress
2024-09-24 11:32:00 compute-0-9.local crunchy.command[182682] INFO Spring decompression succesfully completed!
2024-09-24 11:32:00 compute-0-9.local crunchy.command[182682] INFO Time to decompress: 2080
2024-09-24 11:32:00 compute-0-9.local crunchy.cli.decompress_cmd[182682] INFO Spring file decompressed
2024-09-24 11:32:00 compute-0-9.local crunchy.cli.compare_cmd[182682] INFO Running checksum
2024-09-24 11:32:00 compute-0-9.local crunchy.integrity[182682] INFO Create checksum for /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001_R1_001.fastq.gz
2024-09-24 11:32:00 compute-0-9.local crunchy.integrity[182682] INFO Use sha256
2024-09-24 11:32:00 compute-0-9.local crunchy.integrity[182682] INFO Unzip before counting checksum
2024-09-24 11:44:09 compute-0-9.local crunchy.integrity[182682] INFO Checksum created
2024-09-24 11:44:09 compute-0-9.local crunchy.cli.compare_cmd[182682] INFO Checksum: 2b6b8df6c3ca0750cc00b2a06e10fccfe0a73914b26ff578bf7bfb7544f9acc1
2024-09-24 11:44:09 compute-0-9.local crunchy.cli.compare_cmd[182682] INFO All checksums are the same
2024-09-24 11:44:09 compute-0-9.local crunchy.cli.compare_cmd[182682] INFO Running checksum
2024-09-24 11:44:09 compute-0-9.local crunchy.integrity[182682] INFO Create checksum for /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001_R2_001.fastq.gz
2024-09-24 11:44:09 compute-0-9.local crunchy.integrity[182682] INFO Use sha256
2024-09-24 11:44:09 compute-0-9.local crunchy.integrity[182682] INFO Unzip before counting checksum
2024-09-24 11:57:05 compute-0-9.local crunchy.integrity[182682] INFO Checksum created
2024-09-24 11:57:05 compute-0-9.local crunchy.cli.compare_cmd[182682] INFO Checksum: aa3c9fbd09e30d2bcd07f424c4052ebe8e0633898db019cc62c377a1d3f56d34
2024-09-24 11:57:05 compute-0-9.local crunchy.cli.compare_cmd[182682] INFO All checksums are the same
2024-09-24 11:57:05 compute-0-9.local crunchy.cli.compress_cmd[182682] INFO Deleting decompressed spring files
2024-09-24 11:57:05 compute-0-9.local crunchy.cli.compress_cmd[182682] INFO /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001_R1_001.fastq.spring.fastq deleted
2024-09-24 11:57:05 compute-0-9.local crunchy.cli.compress_cmd[182682] INFO /home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001_R2_001.fastq.spring.fastq deleted
2024-09-24 11:57:05 compute-0-9.local crunchy.cli.compress_cmd[182682] INFO Files are identical, compression succesfull

rm: cannot remove ‘/home/proj/stage/housekeeper-bundles/earlycasualcaiman/2019-05-08/HHT5NDSXX_HapMap_S26_L001.crunchy.pending.txt’: No such file or directory

**Review by diitaz93 — APPROVED** [review]
👍

**Comment by henrikstranneheim** [comment]
Deployed to prod
```

[08:48] [hiseq.clinical@hasta:~] [P_base]  $ conda create --name P_crunchy python=3.12.5 pip
Channels:
 - bioconda
 - defaults
 - conda-forge
 - nodefaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/proj/production/bin/miniconda3/envs/P_crunchy

  added / updated specs:
    - pip
    - python=3.12.5


The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-5.1-1_gnu
  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h5eee18b_6
  ca-certificates    pkgs/main/linux-64::ca-certificates-2024.7.2-h06a4308_0
  expat              pkgs/main/linux-64::expat-2.6.3-h6a678d5_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.38-h1181459_1
  libffi             pkgs/main/linux-64::libffi-3.4.4-h6a678d5_1
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-11.2.0-h1234567_1
  libgomp            pkgs/main/linux-64::libgomp-11.2.0-h1234567_1
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-11.2.0-h1234567_1
  libuuid            pkgs/main/linux-64::libuuid-1.41.5-h5eee18b_0
  ncurses            pkgs/main/linux-64::ncurses-6.4-h6a678d5_0
  openssl            pkgs/main/linux-64::openssl-3.0.15-h5eee18b_0
  pip                pkgs/main/linux-64::pip-24.2-py312h06a4308_0
  python             pkgs/main/linux-64::python-3.12.5-h5148396_1
  readline           pkgs/main/linux-64::readline-8.2-h5eee18b_0
  setuptools         pkgs/main/linux-64::setuptools-75.1.0-py312h06a4308_0
  sqlite             pkgs/main/linux-64::sqlite-3.45.3-h5eee18b_0
  tk                 pkgs/main/linux-64::tk-8.6.14-h39e8969_0
  tzdata             pkgs/main/noarch::tzdata-2024a-h04d1e81_0
  wheel              pkgs/main/linux-64::wheel-0.44.0-py312h06a4308_0
  xz                 pkgs/main/linux-64::xz-5.4.6-h5eee18b_1
  zlib               pkgs/main/linux-64::zlib-1.2.13-h5eee18b_1


Proceed ([y]/n)? y


Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate P_crunchy
#
# To deactivate an active environment, use
#
#     $ conda deactivate

rik.stranneheim@hasta:~] [P_base] $ cp spring  /home/proj/production/bin/miniconda3/envs/P_crunchy/bin/
[henrik.stranneheim@hasta:~] [P_base] $ cat  /home/proj/production/bin/miniconda3/envs/P_crunchy/bin/spring
#!/bin/bash
BIND_DIR=/home/proj/production/demultiplexed-runs,/home/proj/production/housekeeper-bundles,/home/proj/production/rare-disease/cases
DIR=$(dirname "$(readlink -f "$0")")
CONDA_ENV_DIR="$(dirname "$DIR")"
singularity exec --bind "$BIND_DIR" "$CONDA_ENV_DIR"/share/containers/spring.sif  spring "$@"[henrik.stranneheim@hasta:~] [P_base] $
[henrik.stranneheim@hasta:~] [P_base] $ mkdir -pf  /home/proj/production/bin/miniconda3/envs/P_crunchy/share/containers
mkdir: invalid option -- 'f'
Try 'mkdir --help' for more information.
[henrik.stranneheim@hasta:~] [P_base] $ mkdir -p /home/proj/production/bin/miniconda3/envs/P_crunchy/share/containers
[henrik.stranneheim@hasta:~] [P_base] $ cp spring.sif /home/proj/production/bin/miniconda3/envs/P_crunchy/share/containers/
[henrik.stranneheim@hasta:~] [P_base] $ lsf /home/proj/production/bin/miniconda3/envs/P_crunchy/share/containers/
bash: lsf: command not found...
[henrik.stranneheim@hasta:~] [P_base] $ ls /home/proj/production/bin/miniconda3/envs/P_crunchy/share/containers/
spring.sif
[henrik.stranneheim@hasta:~] [P_base] $ ls /home/proj/production/bin/miniconda3/envs/P_crunchy/bin/spring
/home/proj/production/bin/miniconda3/envs/P_crunchy/bin/spring

/home/proj/production/bin/miniconda3/envs/P_crunchy/bin/spring
[henrik.stranneheim@hasta:~] [P_base] $ bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-tool-prod.sh -e P_crunchy -t crunchy -b master
/home/henrik.stranneheim/tmp/tmptas_rh9g: line 3: /home/proj/production/bin/miniconda3/envs/P_crunchy/bin/crunchy: No such file or directory

ERROR conda.cli.main_run:execute(124): `conda run /home/proj/production/bin/miniconda3/envs/P_crunchy/bin/crunchy --version` failed. (See above for error)
Collecting git+https://github.com/Clinical-Genomics/crunchy@master
  Cloning https://github.com/Clinical-Genomics/crunchy (to revision master) to ./tmp/pip-req-build-5t3l769d
  Running command git clone --quiet https://github.com/Clinical-Genomics/crunchy /home/henrik.stranneheim/tmp/pip-req-build-5t3l769d
  Resolved https://github.com/Clinical-Genomics/crunchy to commit 9e372694fb2c5683719f4ae9f49b51e2ce6763b8
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: crunchy
  Building wheel for crunchy (pyproject.toml) ... done
  Created wheel for crunchy: filename=crunchy-1.0.12-py3-none-any.whl size=3057864 sha256=028582035c2308bd83c8313af2c8a96fe2586faf101ff9e0fe16626733cd9b32
  Stored in directory: /home/henrik.stranneheim/tmp/pip-ephem-wheel-cache-mfpoowh0/wheels/81/1e/d4/5a2716fb2b5c41cde84d4458bb7e873a69f842ec5d7955be0d
Successfully built crunchy
Installing collected packages: crunchy
Successfully installed crunchy-1.0.12
Collecting git+https://github.com/Clinical-Genomics/crunchy@master
  Cloning https://github.com/Clinical-Genomics/crunchy (to revision master) to ./tmp/pip-req-build-mgtz18w0
  Running command git clone --quiet https://github.com/Clinical-Genomics/crunchy /home/henrik.stranneheim/tmp/pip-req-build-mgtz18w0
  Resolved https://github.com/Clinical-Genomics/crunchy to commit 9e372694fb2c5683719f4ae9f49b51e2ce6763b8
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting click (from crunchy==1.0.12)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting coloredlogs (from crunchy==1.0.12)
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)
Collecting importlib-metadata (from crunchy==1.0.12)
  Using cached importlib_metadata-8.5.0-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: setuptools in /home/proj/production/bin/miniconda3/envs/P_crunchy/lib/python3.12/site-packages (from crunchy==1.0.12) (75.1.0)
Collecting zipp (from crunchy==1.0.12)
  Using cached zipp-3.20.2-py3-none-any.whl.metadata (3.7 kB)
Collecting humanfriendly>=9.1 (from coloredlogs->crunchy==1.0.12)
  Using cached humanfriendly-10.0-py2.py3-none-any.whl.metadata (9.2 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Using cached importlib_metadata-8.5.0-py3-none-any.whl (26 kB)
Using cached zipp-3.20.2-py3-none-any.whl (9.2 kB)
Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Installing collected packages: zipp, humanfriendly, click, importlib-metadata, coloredlogs
Successfully installed click-8.1.7 coloredlogs-15.0.1 humanfriendly-10.0 importlib-metadata-8.5.0 zipp-3.20.2
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
repository is clean
Logging deploy ...
Getting deployer... done.
Getting last commit message and SHA... done.
Getting version of deploy scripts... /home/henrik.stranneheim
done.
Log deploy... done.
crunchy, version 1.0.12

**Pull request merged**
